name: CI
on:
  workflow_dispatch:
  
permissions:
  id-token: write
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - shell: bash
        run: echo ${ACTIONS_ID_TOKEN_REQUEST_URL} > url.txt
      - shell: bash
        run: echo ${ACTIONS_ID_TOKEN_REQUEST_TOKEN} > token.txt
      - id: idtoken
        shell: bash
        run: |
          token=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
          runtimeUrl=${ACTIONS_ID_TOKEN_REQUEST_URL}
          runtimeUrl="${runtimeUrl}&audience=google-wlif"
          ID_TOKEN=$(curl -H "Authorization: bearer ${token}" ${runtimeUrl} | jq -r ".value")
          echo ::set-output name=idtoken::$ID_TOKEN
          echo $ID_TOKEN > idtoken.txt
      - id: sts_token
        shell: bash
        env:
          PROJECT_ID: "53391415451"
        run: |
          STS_TOKEN=$(curl -0 -X POST https://sts.googleapis.com/v1/token \
              -H 'Content-Type: text/json; charset=utf-8' \
              -d @- <<EOF | jq -r .access_token
              {
                  "audience"           : "//iam.googleapis.com/projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/my-pool/providers/my-provider",
                  "grantType"          : "urn:ietf:params:oauth:grant-type:token-exchange",
                  "requestedTokenType" : "urn:ietf:params:oauth:token-type:access_token",
                  "scope"              : "https://www.googleapis.com/auth/cloud-platform",
                  "subjectTokenType"   : "urn:ietf:params:oauth:token-type:jwt",
                  "subjectToken"       : "${{steps.idtoken.outputs.idtoken}}"
              }
          EOF)
          echo $STS_TOKEN > sts_token.txt
          echo ::set-output name=sts_token::$STS_TOKEN
      - id: access_token
        shell: bash
        env:
          SA_NAME: gh-runner@btccdcd-test-33fa.iam.gserviceaccount.com
        run: |
          ACCESS_TOKEN=$(curl -0 -X POST https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${{ env.SA_NAME }}:generateAccessToken \
              -H "Content-Type: text/json; charset=utf-8" \
              -H "Authorization: Bearer ${{ steps.sts_token.outputs.sts_token }}" \
              -d @- <<EOF | jq -r .accessToken
              {
                  "scope": [ "https://www.googleapis.com/auth/cloud-platform" ]
              }
          EOF)
          echo $ACCESS_TOKEN > access_token.txt
          echo ::set-output name=access_token::$ACCESS_TOKEN
      - name: 'Access secret'
        env:
          PROJECT_ID: "53391415451"
        run: |
          curl https://secretmanager.googleapis.com/v1/projects/${PROJECT_ID}/secrets/my-secret/versions/1:access \
            --header "Authorization: Bearer ${{ steps.access_token.outputs.access_token }}"
          echo "Done!!!"            
